DROP TABLE NOTICE_TW;
DROP SEQUENCE SEQ_NOTICE_NO_TW;
CREATE TABLE NOTICE_TW (
	NOTICE_NO NUMBER PRIMARY KEY,
	NOTICE_TITLE VARCHAR2(100) NOT NULL,
	NOTICE_WRITER VARCHAR2(15) NOT NULL REFERENCES MEMBER(USERID),
	NOTICE_CONTENT VARCHAR2(4000), 
	NOTICE_DATE DATE DEFAULT SYSDATE,
	STATUS VARCHAR2(1) DEFAULT 'Y'
);
CREATE SEQUENCE SEQ_NOTICE_NO_TW;

